### PR TITLE
Fix #138: Implemented Forem app popup on start

### LINKED ISSUE #138: Pop up to migrate users Forem Android app
Pop up to migrate users Forem Android app

All other information can be found here: https://github.com/forem/rfcs/issues/335

Also similar iOS PR: https://github.com/forem/rfcs/issues/181

### PR DESCRIPTION
**Pull request by rt4914**
Fix #138: Implemented Forem app popup on start

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
The Forem android app is now in open-beta which means that we can onboard users from DEV-android to Forem android app. This feature was finalised in https://github.com/forem/rfcs/issues/335 and was also implemented in DEV-iOS app here: https://github.com/forem/DEV-ios/pull/246

## Design Reference
https://www.figma.com/file/E4wztybbeDEKdHVs3vYqtz/Misc----Marketing-Designs?node-id=10%3A2

## New app flow
As soon as user starts the DEV-android app, after the DEV logo screen they will see the pop-up as shown in below screenshots. Here they have two options: (a.) click on Download/Open Button (explained below) or (b.) click anywhere outside the popup (this will close the popup).

As soon as Download button is clicked following steps take place:
1. Check if Forem-android app is already installed and open if yes.
2. If Forem-android app is not found then try to open app in Play Store app
3. If Play Store app is not found then try to open app in browser.

Once they have clicked the "Download button" the pop-up will dismiss and open the app as per above conditions.

If they click on "Compass/Explore" icon on bottom right the app will directly open the Forem app.
If they click on "News" icon on bottom right the app will show the popup again.

Whenever the app redirects to the Forem app the current url from passed so as it open that same page in the Forem app too.

### When Forem app is not installed
Notice in below screenshot that we **do not show "explore/compass" icon** as the Forem app is not available and also the text in the popup/dialog **suggests Installing/Downloading** the app.

### When Forem app is installed
Notice in below screenshot that **we show "explore/compass" icon** as the Forem app is available and also the text in the popup/dialog **suggests Opening** the app.

### CODE REVIEW

**Comment by rt4914** [comment]
Hi @joshpuetz @fdoxyz can you please have a look at this?

**Comment by fdoxyz** [comment]
I can try this one out this afternoon 💯

**Comment by joshpuetz** [comment]
I'm going to try this out as well: it's good motivation for me to set up Android Studio locally!

**Comment by rt4914** [comment]
> I'm going to try this out as well: it's good motivation for me to set up Android Studio locally!
> 
> **Update**: that didn't work 😆 I'll try to debug my Android studio issues another day.
> 
> These screens look terrific @rt4914! Here's some feedback/answers to your questions:
> 
> > I tried implementing the "close" button on top right corner similar to iOS app but it was not looking good so do we actually need that? Or the current flow is fine?
> 
> I don't think the close button is necessary, but does the user have a way to dismiss this dialog without download the Forem app/being jumped away? That's the purpose of the close button on iOS (as an alternative on iOS a user can just 'pull down' on the model to dismiss it).
> 
> > The iOS app has an option to either open the pop-up again or open the installed forem-app directly from DEV app which are implemented in bottom-right corner of screen. Currently android app does not contain the bottom bar. Should I go ahead and implement these two features right now?
> 
> I'm of the opinion that the less work we put into this, the better. Are there stats for how many people are currently using the Android Dev app? On iOS it was like 50 people a month! If it's a similar low number of users, I wouldn't bother implementing a bottom bar JUST for this feature. Displaying this modal on app launch would be enough IMHO.

1. Yes the dialog is dismissable by clicking anywhere outside the dialog box.
2. We actually have a really good DAU/MAU. I will implement the bottom navigation similar to iOS app.
Screenshot 2022-01-21 at 2 44 12 PM

**Comment by rt4914** [comment]
@fdoxyz @joshpuetz I have updated the "New app Flow" and "Screenshot" section in the PR description. Let me know your thoughts.

**Review by fdoxyz — APPROVED** [review]
It worked well in both scenarios (Forem app not installed and also after installing it) 🙌 

LGTM

**Comment by joshpuetz** [comment]
Oh nicely done @rt4914!

**Review by joshpuetz — APPROVED** [review]

**Comment by rt4914** [comment]
Thanks @joshpuetz and @fdoxyz .
 I am merging this now.

**Pull request merged**
